apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: dedicated
          operator: Equal
          values:
            - yellowstone
