deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context faulke/homelab:homelab-cluster-dev
    - kubectl get pods