kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-config-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
