apiVersion: v2
name: nginx
description: A Helm chart for Kubernetes

type: application

version: 0.1.2

appVersion: "latest"

dependencies:
  - name: common
    version: 1.2.1
    repository: https://bjw-s.github.io/helm-charts/