image:
  repository: nginx

service:
  main:
    ports:
      http:
        port: 80

ingress:
  main:
    enabled: true
    hosts:
      - host: nginx.homelab.com
        paths:
          - path: /
            pathType: Prefix
            service:
              port: http
