apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}
spec:
  storageClassName: nfs
  capacity:
    storage: {{ .Values.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock
  {{- with .Values.server }}
  nfs:
    path: {{ .path }}
    server: {{ .address }}
  {{- end }}
