gitops:
  charts:
  - release_name: homelab-dev
    source:
      project:
        id: faulke/homelab
          ref:
            branch: fix-plex
        path: helm
    namespace: default
  # manifest_projects:
  # - id: faulke/homelab
  #   # ref: # either `branch`, `tag` or `commit` can be specified
  #   #   branch: production
  #   #   # commit: <mysha>
  #   #   # tag: v1.0
  #   default_namespace: default
  #   paths:
  #     # Read all YAML files from this directory.
  #   - glob: '/manifests/**/*.yaml'
  #   reconcile_timeout: 3600s
  #   dry_run_strategy: none
  #   prune: true
  #   prune_timeout: 3600s
  #   prune_propagation_policy: foreground
  #   inventory_policy: must_match
