qbittorrent:
  ingress:
    main:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - host: torrents.homelab.com
          paths:
            - path: /
              pathType: Prefix
  env:
    TZ: America/Boise

  nodeSelector:
    dedicated: bitterroot

  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "bitterroot"
      effect: "NoSchedule"
