apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: qbittorrent
spec:
  chart: qbittorrent
  repo: https://k8s-at-home.com/charts/
  version: 13.5.2
  valuesContent: |
    env:
      TZ: America/Boise
      PUID: 1000
      PGID: 1000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: torrents.homelab.com
          paths:
          - path: /
            pathType: Prefix
    nodeSelector:
      dedicated: bitterroot
    tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "bitterroot"
      effect: "NoSchedule"   